/* Banque de questions du Quiz — culture générale (Monde + Madagascar).
   Format : { c: catégorie, l: niveau (1-3), q: question, o: options, a: index de la bonne réponse } */
"use strict";

window.QUIZ_DATA = [
  // ------------------------------------------------------------------ NIVEAU 1 — FACILE
  { c: "Monde", l: 1, q: "Quelle est la capitale de la France ?", o: ["Marseille", "Paris", "Lyon", "Toulouse"], a: 1 },
  { c: "Monde", l: 1, q: "Combien de continents y a-t-il sur Terre ?", o: ["6", "5", "8", "7"], a: 3 },
  { c: "Monde", l: 1, q: "Quel est le plus grand océan du monde ?", o: ["Atlantique", "Indien", "Pacifique", "Arctique"], a: 2 },
  { c: "Madagascar", l: 1, q: "Quelle est la capitale de Madagascar ?", o: ["Toamasina", "Antananarivo", "Antsirabe", "Fianarantsoa"], a: 1 },
  { c: "Madagascar", l: 1, q: "Quelle est la monnaie de Madagascar ?", o: ["le franc CFA", "l'euro", "le shilling", "l'ariary"], a: 3 },
  { c: "Madagascar", l: 1, q: "Quel océan borde Madagascar ?", o: ["l'océan Indien", "l'océan Atlantique", "l'océan Pacifique", "l'océan Austral"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel petit primate nocturne est le symbole de Madagascar ?", o: ["le koala", "le paresseux", "le lémur", "le singe-écureuil"], a: 2 },
  { c: "Madagascar", l: 1, q: "De quelles couleurs est le drapeau malgache ?", o: ["Bleu, jaune et rouge", "Rouge, blanc et bleu", "Vert, jaune et noir", "Blanc, rouge et vert"], a: 3 },
  { c: "Monde", l: 1, q: "Quel pays a la forme d'une botte ?", o: ["le Japon", "le Chili", "l'Italie", "la France"], a: 2 },
  { c: "Monde", l: 1, q: "Combien de joueurs de football par équipe sur le terrain ?", o: ["11", "10", "12", "9"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la monnaie de l'Union européenne ?", o: ["le dollar", "l'euro", "la livre sterling", "le franc"], a: 1 },
  { c: "Monde", l: 1, q: "Qui a peint la Joconde ?", o: ["Claude Monet", "Pablo Picasso", "Rembrandt", "Léonard de Vinci"], a: 3 },
  { c: "Monde", l: 1, q: "Quel est le plus grand désert chaud du monde ?", o: ["le Sahara", "le Gobi", "le Kalahari", "l'Atacama"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de l'Égypte ?", o: ["Alexandrie", "Louxor", "Le Caire", "Gizeh"], a: 2 },
  { c: "Monde", l: 1, q: "Quelle planète est la plus proche du Soleil ?", o: ["Vénus", "Mercure", "Terre", "Mars"], a: 1 },
  { c: "Monde", l: 1, q: "Combien de pattes a une araignée ?", o: ["6", "10", "8", "4"], a: 2 },
  { c: "Monde", l: 1, q: "Quel est l'animal terrestre le plus rapide ?", o: ["le lion", "la gazelle", "l'autruche", "le guépard"], a: 3 },
  { c: "Monde", l: 1, q: "Quel fleuve traverse Paris ?", o: ["la Loire", "la Seine", "le Rhône", "la Garonne"], a: 1 },
  { c: "Monde", l: 1, q: "Combien de lettres compte l'alphabet français ?", o: ["24", "26", "28", "25"], a: 1 },
  { c: "Madagascar", l: 1, q: "Quel est le plat national malgache (bœuf, herbes, tomates) ?", o: ["le couscous", "la lasagne", "le romazava", "le pot-au-feu"], a: 2 },
  { c: "Madagascar", l: 1, q: "Quel instrument traditionnel en bambou est le symbole musical de Madagascar ?", o: ["la kora", "la valiha", "le banjo", "la guitare"], a: 1 },
  { c: "Monde", l: 1, q: "Combien de côtés a un hexagone ?", o: ["5", "7", "6", "8"], a: 2 },
  { c: "Monde", l: 1, q: "Quelle couleur obtient-on en mélangeant du bleu et du jaune ?", o: ["l'orange", "le violet", "le marron", "le vert"], a: 3 },
  { c: "Monde", l: 1, q: "Combien de pattes a un insecte ?", o: ["8", "6", "4", "10"], a: 1 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de l'Italie ?", o: ["Rome", "Milan", "Naples", "Venise"], a: 0 },
  { c: "Monde", l: 1, q: "Quel pays a pour capitale Tokyo ?", o: ["la Chine", "la Corée du Sud", "le Japon", "le Vietnam"], a: 2 },
  { c: "Monde", l: 1, q: "Combien de fuseaux horaires compte la Terre ?", o: ["24", "12", "36", "18"], a: 0 },
  { c: "Monde", l: 1, q: "Qui a bâti les pyramides de Gizeh ?", o: ["les Romains", "les Égyptiens anciens", "les Grecs", "les Perses"], a: 1 },
  { c: "Monde", l: 1, q: "En quelle année Christophe Colomb atteint-il l'Amérique ?", o: ["1500", "1498", "1512", "1492"], a: 3 },
  { c: "Monde", l: 1, q: "Quel dinosaure avait trois cornes ?", o: ["le Tyrannosaure", "le Stégosaure", "le Tricératops", "le Velociraptor"], a: 2 },
  { c: "Monde", l: 1, q: "Combien de pattes a un crabe ?", o: ["6", "8", "10", "4"], a: 2 },
  { c: "Monde", l: 1, q: "Quel animal pond des œufs parmi ces-là ?", o: ["la vache", "le dauphin", "la poule", "le chien"], a: 2 },

  // ------------------------------------------------------------------ NIVEAU 2 — MOYEN
  { c: "Monde", l: 2, q: "En quelle année éclate la Révolution française ?", o: ["1776", "1789", "1799", "1804"], a: 1 },
  { c: "Monde", l: 2, q: "Qui fut le premier président des États-Unis ?", o: ["Thomas Jefferson", "John Adams", "George Washington", "Abraham Lincoln"], a: 2 },
  { c: "Monde", l: 2, q: "Quelle est la capitale du Canada ?", o: ["Toronto", "Ottawa", "Montréal", "Vancouver"], a: 1 },
  { c: "Monde", l: 2, q: "Quel est le plus haut sommet du monde ?", o: ["le K2", "le Kangchenjunga", "le Denali", "l'Everest"], a: 3 },
  { c: "Monde", l: 2, q: "Combien d'États membres compte l'Union européenne ?", o: ["27", "28", "26", "30"], a: 0 },
  { c: "Monde", l: 2, q: "Quel pays a remporté le plus de Coupes du Monde de football ?", o: ["l'Allemagne", "l'Italie", "le Brésil", "l'Argentine"], a: 2 },
  { c: "Monde", l: 2, q: "Qui a écrit « Les Misérables » ?", o: ["Émile Zola", "Victor Hugo", "Alexandre Dumas", "Honoré de Balzac"], a: 1 },
  { c: "Monde", l: 2, q: "Combien de joueurs de basket par équipe sur le terrain ?", o: ["6", "5", "7", "4"], a: 1 },
  { c: "Monde", l: 2, q: "Combien de jours comporte une année bissextile ?", o: ["365", "364", "366", "360"], a: 2 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de l'Australie ?", o: ["Sydney", "Melbourne", "Canberra", "Brisbane"], a: 2 },
  { c: "Monde", l: 2, q: "Quel peintre s'est coupé une oreille ?", o: ["Vincent van Gogh", "Paul Gauguin", "Claude Monet", "Paul Cézanne"], a: 0 },
  { c: "Monde", l: 2, q: "Combien de chromosomes contient une cellule humaine ?", o: ["44", "46", "23", "48"], a: 1 },
  { c: "Monde", l: 2, q: "En quelle année l'homme a-t-il marché sur la Lune ?", o: ["1961", "1965", "1969", "1972"], a: 2 },
  { c: "Madagascar", l: 2, q: "Combien de régions administratives compte Madagascar ?", o: ["18", "6", "22", "23"], a: 3 },
  { c: "Madagascar", l: 2, q: "En quelle année Madagascar accède-t-il à l'indépendance ?", o: ["1960", "1958", "1947", "1962"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le « kabary » est…", o: ["une danse guerrière", "un art oratoire", "un plat de riz", "un instrument de percussion"], a: 1 },
  { c: "Madagascar", l: 2, q: "Le « famadihana » est une tradition malgache qui consiste à…", o: ["retourner les défunts", "célébrer la récolte du riz", "fêter la circoncision", "organiser un mariage"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quelle ville est surnommée « Diego » ?", o: ["Mahajanga", "Antsiranana", "Toamasina", "Toliara"], a: 1 },
  { c: "Madagascar", l: 2, q: "Quel peuple des Hautes Terres est réputé pour ses rizières en terrasses ?", o: ["les Sakalava", "les Vezo", "les Betsileo", "les Antandroy"], a: 2 },
  { c: "Madagascar", l: 2, q: "Quel parc national du sud de Madagascar est célèbre pour ses formations rocheuses ?", o: ["Ranomafana", "Isalo", "Andasibe", "Ankarafantsika"], a: 1 },
  { c: "Madagascar", l: 2, q: "Quelle île touristique se trouve au large de la côte nord-ouest de Madagascar ?", o: ["Nosy Be", "Nosy Boraha", "la Réunion", "Maurice"], a: 0 },
  { c: "Monde", l: 2, q: "Qui a découvert la pénicilline ?", o: ["Louis Pasteur", "Robert Koch", "Alexander Fleming", "Joseph Lister"], a: 2 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de la Nouvelle-Zélande ?", o: ["Auckland", "Wellington", "Sydney", "Christchurch"], a: 1 },
  { c: "Monde", l: 2, q: "Combien de pays compte l'Afrique ?", o: ["50", "54", "48", "55"], a: 1 },
  { c: "Monde", l: 2, q: "Qui a peint « Le Cri » ?", o: ["Edvard Munch", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], a: 0 },
  { c: "Monde", l: 2, q: "Quel fleuve traverse Le Caire ?", o: ["le Congo", "le Nil", "le Niger", "le Zamèze"], a: 1 },
  { c: "Monde", l: 2, q: "Combien de joueurs de volley-ball par équipe sur le terrain ?", o: ["5", "7", "6", "4"], a: 2 },
  { c: "Monde", l: 2, q: "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", o: ["les Alpes", "les Pyrénées", "l'Oural", "le Caucase"], a: 2 },
  { c: "Madagascar", l: 2, q: "Le zebu joue quel rôle dans la société malgache ?", o: ["animal de prestige et d'offrande", "poisson sacré", "oiseau de chasse", "insecte sacré"], a: 0 },
  { c: "Monde", l: 2, q: "Qui a écrit « Le Prince » ?", o: ["Platon", "Aristote", "Nicolas Machiavel", "Cervantès"], a: 2 },
  { c: "Madagascar", l: 2, q: "Quel surnom les Malgaches donnent-ils parfois à Antananarivo ?", o: ["Tana", "Tana-city", "la Blanche", "le Port"], a: 0 },

  // ------------------------------------------------------------------ NIVEAU 3 — DIFFICILE
  { c: "Monde", l: 3, q: "Quel est le plus petit pays du monde ?", o: ["Monaco", "le Vatican", "San Marins", "Liechtenstein"], a: 1 },
  { c: "Monde", l: 3, q: "Combien d'États membres compte l'ONU ?", o: ["195", "190", "193", "200"], a: 2 },
  { c: "Monde", l: 3, q: "Quel gaz est le plus abondant dans l'atmosphère ?", o: ["l'oxygène", "l'azote", "l'argon", "le dioxyde de carbone"], a: 1 },
  { c: "Monde", l: 3, q: "Combien de temps met la lumière du Soleil à atteindre la Terre ?", o: ["environ 8 minutes", "environ 1 minute", "environ 30 secondes", "environ 2 heures"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la profondeur maximale connue de l'océan ?", o: ["environ 5 000 m", "environ 3 000 m", "environ 11 000 m", "environ 20 000 m"], a: 2 },
  { c: "Monde", l: 3, q: "En quelle année le mur de Berlin tombe-t-il ?", o: ["1991", "1985", "1989", "1990"], a: 2 },
  { c: "Monde", l: 3, q: "Quel empire a bâti Machu Picchu ?", o: ["les Aztèques", "les Maya", "les Khmers", "les Incas"], a: 3 },
  { c: "Monde", l: 3, q: "Quelle planète tourne à l'envers (rétrograde) ?", o: ["Vénus", "Mars", "Mercure", "Jupiter"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel est le plus haut sommet de Madagascar ?", o: ["le Pic Boby", "le Maromokotro", "l'Ankaratra", "le Tsiafajavona"], a: 1 },
  { c: "Madagascar", l: 3, q: "Combien d'espèces de lémuriens endémiques recense-t-on environ ?", o: ["une dizaine", "une cinquantaine", "plus de 100", "plus de 500"], a: 2 },
  { c: "Madagascar", l: 3, q: "Qui fut le premier président de la République malgache ?", o: ["Didier Ratsiraka", "Philibert Tsiranana", "Albert Razafindrakoto", "Hery Rajaonarimampianina"], a: 1 },
  { c: "Madagascar", l: 3, q: "Qui fut la dernière reine de Madagascar ?", o: ["Ranavalona I", "Ranavalona II", "Ranavalona III", "Zanakandriana"], a: 2 },
  { c: "Madagascar", l: 3, q: "En quelle année Madagascar devient-elle une colonie française ?", o: ["1885", "1896", "1900", "1912"], a: 1 },
  { c: "Madagascar", l: 3, q: "Le « sampy » était…", o: ["un talisman royal", "une danse sacrée", "un tambour", "une épée de guerre"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel est le plus long fleuve de Madagascar ?", o: ["le Betsiboka", "l'Ikopa", "le Mangoky", "la Mananara"], a: 2 },
  { c: "Madagascar", l: 3, q: "Le « hira gasy » est…", o: ["un chant populaire traditionnel", "un rite funéraire", "une course de zebus", "un type de pirogue"], a: 0 },
  { c: "Monde", l: 3, q: "Combien de muscles compte le corps humain ?", o: ["environ 200", "environ 640", "environ 1 000", "environ 300"], a: 1 },
  { c: "Monde", l: 3, q: "Quel est le plus petit os du corps humain ?", o: ["l'étrier", "la phalange", "l'incisive", "le calcaneus"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la mer la plus salée du monde ?", o: ["la Mer Rouge", "la Mer Morte", "la Mer Noire", "la Baltique"], a: 1 },
  { c: "Monde", l: 3, q: "Combien de cœurs a une pieuvre ?", o: ["1", "2", "4", "3"], a: 3 },
  { c: "Monde", l: 3, q: "Combien de fuseaux horaires compte la Chine ?", o: ["1", "2", "4", "5"], a: 0 },
  { c: "Monde", l: 3, q: "Combien de pays compte l'Amérique du Sud ?", o: ["10", "15", "12", "13"], a: 2 },
  { c: "Monde", l: 3, q: "Quelle capitale est traversée par l'équateur ?", o: ["Bogota", "Quito", "Nairobi", "Jakarta"], a: 1 },
  { c: "Monde", l: 3, q: "Qui a formulé « Je pense, donc je suis » ?", o: ["Blaise Pascal", "Emmanuel Kant", "René Descartes", "John Locke"], a: 2 },
  { c: "Monde", l: 3, q: "Combien de lettres compte l'alphabet russe ?", o: ["31", "33", "35", "29"], a: 1 },
  { c: "Madagascar", l: 3, q: "Environ combien d'habitants compte Madagascar ?", o: ["10 millions", "50 millions", "30 millions", "80 millions"], a: 2 },
  { c: "Monde", l: 3, q: "Combien d'États fédérés compte l'Allemagne ?", o: ["14", "16", "18", "20"], a: 1 },
  { c: "Monde", l: 3, q: "Quelle est la durée réglementaire d'un match de football ?", o: ["80 minutes", "100 minutes", "90 minutes", "95 minutes"], a: 2 },
  { c: "Monde", l: 3, q: "Combien de joueurs de handball par équipe sur le terrain ?", o: ["6", "7", "8", "5"], a: 1 },
  { c: "Monde", l: 3, q: "Quel pays a remporté la toute première Coupe du Monde de football (1930) ?", o: ["le Brésil", "l'Italie", "l'Uruguay", "l'Argentine"], a: 2 },
  { c: "Monde", l: 3, q: "Combien d'os compte le squelette d'un adulte ?", o: ["206", "150", "300", "250"], a: 0 },
  { c: "Monde", l: 3, q: "Quel est le record du monde du 100 mètres (Usain Bolt) ?", o: ["9,69 s", "9,58 s", "9,50 s", "9,72 s"], a: 1 },
  { c: "Madagascar", l: 3, q: "Quel est le nom de l'aéroport international d'Antananarivo ?", o: ["Fascene", "Ivato", "Avaratra", "Vatomandry"], a: 1 },
  { c: "Madagascar", l: 3, q: "Combien de provinces historiques Madagascar comptait-elle avant les régions ?", o: ["4", "5", "8", "6"], a: 3 },
  { c: "Madagascar", l: 3, q: "Le « tromba » est…", o: ["un rite de possession spirite", "un type de barque", "un plat de fruits de mer", "une cérémonie du riz"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la langue la plus parlée au monde en nombre total de locuteurs ?", o: ["l'anglais", "le mandarin", "l'espagnol", "l'hindi"], a: 0 },
  { c: "Monde", l: 3, q: "Qui a écrit « L'Étranger » ?", o: ["Jean-Paul Sartre", "Albert Camus", "Marcel Proust", "André Gide"], a: 1 },
// ---------------------------------------------------------- MADAGASCAR — FACILE
  { c: "Madagascar", l: 1, q: "Quel océan borde Madagascar à l'est ?", o: ["L'océan Pacifique", "L'océan Atlantique", "L'océan Indien", "L'océan Arctique"], a: 2 },
  { c: "Madagascar", l: 1, q: "Quelle langue est officielle à Madagascar ?", o: ["Le malgache", "Le portugais", "L'anglais", "Le swahili"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel animal est l'emblème de Madagascar ?", o: ["Le lémurien", "Le panda", "Le koala", "Le kangourou"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel est le plat national malgache ?", o: ["La romazava", "Le poulet-yassa", "Le sushi", "Le tacos"], a: 0 },
  { c: "Madagascar", l: 1, q: "De quel pays Madagascar a-t-elle obtenu son indépendance en 1960 ?", o: ["La France", "Le Royaume-Uni", "Le Portugal", "La Belgique"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quelle est la fête nationale de Madagascar ?", o: ["Le 26 juin", "Le 14 juillet", "Le 1er janvier", "Le 15 août"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel aliment est la base de l'alimentation malgache ?", o: ["Le riz", "Le pain", "Les pâtes", "Le maïs"], a: 0 },
  { c: "Madagascar", l: 1, q: "Madagascar est la plus grande île de quel océan ?", o: ["De l'océan Indien", "De l'océan Pacifique", "De l'océan Atlantique", "De l'océan Arctique"], a: 0 },
  { c: "Madagascar", l: 1, q: "L'Allée des Baobabs se trouve près de quelle ville ?", o: ["Morondava", "Mahajanga", "Toliara", "Antsiranana"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel est l'indicatif téléphonique de Madagascar ?", o: ["+261", "+254", "+212", "+27"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quelle ville est le principal port de Madagascar ?", o: ["Toamasina", "Antsirabe", "Antsiranana", "Fianarantsoa"], a: 0 },
  { c: "Madagascar", l: 1, q: "Combien de couleurs compte le drapeau malgache ?", o: ["3", "2", "4", "5"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel sport est le plus populaire à Madagascar ?", o: ["Le rugby à XV", "Le baseball", "Le hockey sur glace", "Le football de plage"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quelle île est surnommée « l'île aux parfums » ?", o: ["Nosy Be", "La Réunion", "Maurice", "Zanzibar"], a: 0 },

  // ---------------------------------------------------------- MADAGASCAR — MOYEN
  { c: "Madagascar", l: 2, q: "Le canal des Pangalanes longe la côte …", o: ["est", "ouest", "nord", "sud"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quel canal sépare Madagascar du continent africain ?", o: ["Le canal du Mozambique", "Le détroit de Malacca", "Le détroit de Gibraltar", "Le détroit de Béring"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le « fady » dans la culture malgache désigne…", o: ["un interdit, une règle traditionnelle", "une danse festive", "un plat épicé", "un instrument de musique"], a: 0 },
  { c: "Madagascar", l: 2, q: "La « famadihana » est la tradition de…", o: ["retourner les dépouilles de ses aïeux", "se marier en groupe", "construire des pirogues", "pêcher en mer"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le valiha est un instrument traditionnel malgache fabriqué en…", o: ["bambou", "bois de santal", "os", "coque de noix de coco"], a: 0 },
  { c: "Madagascar", l: 2, q: "Les Tsingy de Bemaraha sont de…", o: ["hautes aiguilles de calcaire", "volcans actifs", "dunes de sable", "glaciers"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quel parc national est célèbre pour ses indris (lémuriens) ?", o: ["Andasibe-Mantadia", "Isalo", "Nosy Be", "Ile Sainte-Marie"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le parc national de l'Isalo se trouve…", o: ["dans le sud du pays", "au nord-ouest", "sur la côte est", "à Antananarivo"], a: 0 },
  { c: "Madagascar", l: 2, q: "Antananarivo se situe sur…", o: ["les hautes terres", "le littoral", "une île volcanique", "le delta d'un fleuve"], a: 0 },
  { c: "Madagascar", l: 2, q: "L'aye-aye est…", o: ["un lémurien au long doigt qui se nourrit d'insectes", "un oiseau nocturne", "un poisson des récifs", "un reptile venimeux"], a: 0 },
  { c: "Madagascar", l: 2, q: "Madagascar est l'un des premiers mondiaux pour la production de…", o: ["vanille", "cannelle", "curcuma", "cardamome"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quelle ville est surnommée la « ville d'eau » ?", o: ["Antsirabe", "Toliara", "Mahajanga", "Toamasina"], a: 0 },
  { c: "Madagascar", l: 2, q: "Fianarantsoa est surtout connue pour…", o: ["ses universités", "ses mines d'or", "son port en eau profonde", "ses pyramides"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le fosa est…", o: ["un mammifère carnivore endémique de Madagascar", "un oiseau migrateur", "un poisson des rivières", "un insecte géant"], a: 0 },
  { c: "Madagascar", l: 2, q: "L'aéroport international d'Ivato dessert quelle ville ?", o: ["Antananarivo", "Mahajanga", "Toliara", "Antsirabe"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quel est le surnom de l'équipe nationale de football malgache ?", o: ["Les Barea", "Les Zébus", "Les Baobabs", "Les Lémuriens"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le zébu est important dans la culture malgache car il est…", o: ["symbole de richesse et servant de monnaie d'échange", "un animal sacré qu'on ne consomme jamais", "interdit en dehors des villes", "réservé aux seuls éleveurs étrangers"], a: 0 },

  // ---------------------------------------------------------- MADAGASCAR — DIFFICILE
  { c: "Madagascar", l: 3, q: "Quelle était la monnaie de Madagascar avant l'ariary ?", o: ["Le franc malgache", "Le real", "La livre", "Le peso"], a: 0 },
  { c: "Madagascar", l: 3, q: "Madagascar est devenue colonie française en…", o: ["1896", "1885", "1914", "1947"], a: 0 },
  { c: "Madagascar", l: 3, q: "Le « kabary » est l'art de…", o: ["l'éloquence oratoire", "la sculpture sur bois", "la pêche hauturière", "la tissure de soie"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel grand poète malgache est mort en 1937 ?", o: ["Jean-Joseph Rabearivelo", "Victor Hugo", "Aimé Césaire", "Léopold Sédar Senghor"], a: 0 },
  { c: "Madagascar", l: 3, q: "Le salegy est…", o: ["un genre musical du nord de Madagascar", "un plat de la côte sud", "un vêtement royal", "un bateau de pêche"], a: 0 },
  { c: "Madagascar", l: 3, q: "La reine Ranavalona Ière est célèbre pour…", o: ["avoir résisté à la pression des puissances étrangères", "avoir découvert la route des Indes", "avoir inventé l'imprimerie", "avoir bâti les pyramides"], a: 0 },
  { c: "Madagascar", l: 3, q: "En 1942, quelle puissance a envahi Madagascar pour empêcher les Japonais de s'en emparer ?", o: ["Le Royaume-Uni", "L'Italie", "L'Allemagne", "Les États-Unis"], a: 0 },
  { c: "Madagascar", l: 3, q: "L'Imerina est…", o: ["la région des hauts plateaux autour d'Antananarivo", "la côte nord-ouest", "l'île de Nosy Be", "le sud semi-aride"], a: 0 },
  { c: "Madagascar", l: 3, q: "Le pic Boby (Andringitra) est…", o: ["le deuxième plus haut sommet de Madagascar", "le plus haut sommet du pays", "un volcan actif", "le point le plus bas du pays"], a: 0 },
  { c: "Madagascar", l: 3, q: "Ambositra est célèbre pour sa…", o: ["sculpture sur bois", "verrerie", "orfèvrerie d'argent", "poterie émaillée"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quelle île est célèbre pour l'observation des baleines à bosse ?", o: ["L'île Sainte-Marie (Nosy Boraha)", "Nosy Be", "L'île Tromelin", "L'île Juan de Nova"], a: 0 },
  { c: "Madagascar", l: 3, q: "Antalaha est surnommée la…", o: ["capitale de la vanille", "cité des pêcheurs", "ville des tisserands", "capitale du caoutchouc"], a: 0 },
  { c: "Madagascar", l: 3, q: "La devise « Tanindrazana, Fahafanasana, Fandrosoana » signifie…", o: ["Amour de la patrie, Liberté, Progrès", "Travail, Famille, Patrie", "Unité, Travail, Progrès", "Paix, Justice, Travail"], a: 0 },
  { c: "Madagascar", l: 3, q: "En quelle année Madagascar a-t-elle célébré ses 60 ans d'indépendance ?", o: ["2020", "2010", "2030", "1996"], a: 0 },
  { c: "Madagascar", l: 3, q: "Qui fut le Premier ministre qui épousa successivement trois reines malgaches ?", o: ["Rainilaiarivony", "Radama II", "Ratsimilaho", "Rakoto"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel territoire français se trouve au nord-ouest de Madagascar ?", o: ["Mayotte", "La Réunion", "Saint-Pierre-et-Miquelon", "Wallis-et-Futuna"], a: 0 },

  // ---------------------------------------------------------- MONDE — FACILE
  { c: "Monde", l: 1, q: "Quel est le plus grand pays du monde ?", o: ["La Russie", "Le Canada", "La Chine", "Les États-Unis"], a: 0 },
  { c: "Monde", l: 1, q: "Depuis 2023, quel est le pays le plus peuplé du monde ?", o: ["L'Inde", "La Chine", "Les États-Unis", "L'Indonésie"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale du Japon ?", o: ["Tokyo", "Kyoto", "Osaka", "Séoul"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la plus grande planète du système solaire ?", o: ["Jupiter", "Saturne", "Neptune", "La Terre"], a: 0 },
  { c: "Monde", l: 1, q: "Quel est le plus haut sommet de la Terre ?", o: ["L'Everest", "Le Kilimandjaro", "Le Mont Blanc", "L'Aconcagua"], a: 0 },
  { c: "Monde", l: 1, q: "Quel pays a une feuille d'érable sur son drapeau ?", o: ["Le Canada", "Le Japon", "Le Brésil", "L'Italie"], a: 0 },
  { c: "Monde", l: 1, q: "Quel pays est célèbre pour ses fjords ?", o: ["La Norvège", "L'Espagne", "Le Mexique", "L'Égypte"], a: 0 },
  { c: "Monde", l: 1, q: "Le Colisée se trouve dans quelle ville ?", o: ["Rome", "Athènes", "Madrid", "Istanbul"], a: 0 },
  { c: "Monde", l: 1, q: "Machu Picchu se trouve dans quel pays ?", o: ["Le Pérou", "Le Mexique", "Le Chili", "La Bolivie"], a: 0 },
  { c: "Monde", l: 1, q: "Les pyramides de Gizeh se trouvent en…", o: ["Égypte", "Soudan", "Mexique", "Grèce"], a: 0 },
  { c: "Monde", l: 1, q: "Quelles couleurs dominent le drapeau du Brésil ?", o: ["Le vert et le jaune", "Le rouge et le noir", "Le bleu et le blanc", "L'orange et le vert"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la langue officielle du Brésil ?", o: ["Le portugais", "L'espagnol", "Le français", "L'anglais"], a: 0 },

  // ---------------------------------------------------------- MONDE — MOYEN
  { c: "Monde", l: 2, q: "En quelle année a commencé la Seconde Guerre mondiale ?", o: ["1939", "1914", "1945", "1918"], a: 0 },
  { c: "Monde", l: 2, q: "En quelle année Christophe Colomb a-t-il atteint l'Amérique ?", o: ["1492", "1521", "1453", "1607"], a: 0 },
  { c: "Monde", l: 2, q: "En quelle année a commencé la Révolution française ?", o: ["1789", "1776", "1804", "1815"], a: 0 },
  { c: "Monde", l: 2, q: "En quelle année le mur de Berlin est-il tombé ?", o: ["1989", "1975", "1991", "1961"], a: 0 },
  { c: "Monde", l: 2, q: "Qui fut le premier homme à marcher sur la Lune ?", o: ["Neil Armstrong", "Youri Gagarine", "John Glenn", "Michael Collins"], a: 0 },
  { c: "Monde", l: 2, q: "Qui fut le premier homme dans l'espace ?", o: ["Youri Gagarine", "Neil Armstrong", "John Glenn", "Buzz Aldrin"], a: 0 },
  { c: "Monde", l: 2, q: "Le détroit de Gibraltar sépare l'Europe de…", o: ["l'Afrique", "l'Asie", "l'Amérique", "l'Océanie"], a: 0 },
  { c: "Monde", l: 2, q: "Quel canal relie la mer Méditerranée à la mer Rouge ?", o: ["Le canal de Suez", "Le canal de Panama", "Le canal du Doubs", "Le canal de Kiel"], a: 0 },
  { c: "Monde", l: 2, q: "Les Andes longent quel continent ?", o: ["L'Amérique du Sud", "L'Asie", "L'Afrique", "L'Europe"], a: 0 },
  { c: "Monde", l: 2, q: "Quel est le plus grand lac du monde par sa surface ?", o: ["La mer Caspienne", "Le lac Supérieur", "Le lac Victoria", "Le lac Baïkal"], a: 0 },
  { c: "Monde", l: 2, q: "Quel fleuve a le plus grand débit au monde ?", o: ["L'Amazone", "Le Nil", "Le Congo", "Le Mississippi"], a: 0 },
  { c: "Monde", l: 2, q: "Quel de ces pays est traversé par l'équateur ?", o: ["Le Brésil", "Le Canada", "L'Australie", "La Norvège"], a: 0 },
  { c: "Monde", l: 2, q: "Qui a peint le tableau « Les Tournesols » ?", o: ["Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Salvador Dalí"], a: 0 },

  // ---------------------------------------------------------- MONDE — DIFFICILE
  { c: "Monde", l: 3, q: "Quelle est l'unité de mesure de la force ?", o: ["Le newton", "Le watt", "Le joule", "Le volt"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est environ la vitesse de la lumière dans le vide ?", o: ["300 000 km/s", "30 000 km/s", "3 000 km/s", "3 000 000 km/s"], a: 0 },
  { c: "Monde", l: 3, q: "Combien d'os compte le corps humain adulte ?", o: ["206", "150", "300", "412"], a: 0 },
  { c: "Monde", l: 3, q: "Le corail est…", o: ["un animal", "un végétal", "un minéral", "un champignon"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle planète est la plus chaude du système solaire ?", o: ["Vénus", "Mercure", "Mars", "Jupiter"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la monnaie de la Thaïlande ?", o: ["Le baht", "Le roupie", "Le dong", "Le yuan"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la monnaie de la Pologne ?", o: ["Le zloty", "Le forint", "La couronne", "L'euro"], a: 0 },
  { c: "Monde", l: 3, q: "Qui fut le premier empereur romain ?", o: ["Auguste", "Jules César", "Néron", "Trajan"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle civilisation a construit Machu Picchu ?", o: ["Les Incas", "Les Aztèques", "Les Mayas", "Les Romains"], a: 0 },
  { c: "Monde", l: 3, q: "En quelle année l'Union soviétique s'est-elle effondrée ?", o: ["1991", "1989", "1975", "1945"], a: 0 },
  { c: "Monde", l: 3, q: "Dans quelle ville siège l'Organisation mondiale de la santé (OMS) ?", o: ["Genève", "Paris", "New York", "Bruxelles"], a: 0 },
  { c: "Monde", l: 3, q: "En quelle année l'Organisation des Nations unies a-t-elle été fondée ?", o: ["1945", "1918", "1939", "1960"], a: 0 },
  { c: "Monde", l: 3, q: "Quel pays a quitté l'Union européenne en 2020 ?", o: ["Le Royaume-Uni", "La Suède", "Le Danemark", "La Pologne"], a: 0 },
  { c: "Monde", l: 3, q: "Qui a sculpté le David de Florence ?", o: ["Michel-Ange", "Auguste Rodin", "Léonard de Vinci", "Pablo Picasso"], a: 0 },
  { c: "Monde", l: 3, q: "Le lac Baïkal est le plus grand lac d'eau douce du monde…", o: ["par son volume d'eau total", "par sa superficie", "par sa longueur", "par le nombre de ses îles"], a: 0 },
  { c: "Monde", l: 3, q: "Quel détroit sépare l'Asie de l'Amérique ?", o: ["Le détroit de Béring", "Le détroit de Malacca", "Le détroit d'Ormuz", "Le détroit de Taïwan"], a: 0 },
  { c: "Monde", l: 3, q: "Quel est le plus long fleuve d'Europe ?", o: ["La Volga", "Le Danube", "Le Rhin", "La Seine"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle mer a la salinité la plus élevée ?", o: ["La mer Morte", "La mer Rouge", "La mer Noire", "La Baltique"], a: 0 },
  { c: "Monde", l: 3, q: "Quel roi de France a dit « L'État, c'est moi » ?", o: ["Louis XIV", "Louis XVI", "Napoléon Ier", "Henri IV"], a: 0 },
  // ------------------------------------------------------------------ CRÉATEUR DU QUIZ
  { c: "Quiz", l: 1, q: "Qui a créé ce Quiz ?", o: ["Hery", "Miora", "Tsikynambs", "Fara"], a: 2 },
  { c: "Quiz", l: 1, q: "Quel est le vrai nom de l auteur Tsikynambs ?", o: ["Volana Rija", "NAMBININTSOA Tsiky Fanantenana", "Tojo Andry", "Rakoto Hery"], a: 1 },
  // ------------------------------------------------------------------ BONUS
  { c: "Monde", l: 2, q: "Quelle est la plus grosse planète du système solaire ?", o: ["Saturne","Jupiter","Neptune","Terre"], a: 1 },
  // ------------------------------------------------------------ BONUS 2 (260)
  { c: "Madagascar", l: 2, q: "Quel peuple vit principalement à l'ouest de Madagascar ?", o: ["les Sakalava","les Betsileo","les Merina","les Betsimisaraka"], a: 0 },
  { c: "Madagascar", l: 1, q: "Quel est l'ancien nom de Toamasina ?", o: ["Tamatave","Toliara","Majunga","Antsirabe"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quel est l'ancien nom de Mahajanga ?", o: ["Majunga","Tamatave","Tuléar","Fianarantsoa"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quel est l'ancien nom de Toliara ?", o: ["Tuléar","Tamatave","Majunga","Antsirabe"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quel est le nom actuel de Fort-Dauphin ?", o: ["Tolagnaro","Manakara","Mahanoro","Farafangana"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel est le nom du train historique reliant Antananarivo à Toamasina ?", o: ["le Train de l'Est","le Train du Sud","l'Express des hauts plateaux","le Rail Bleu"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel est le nom de l'aéroport de Nosy Be ?", o: ["Fascene","Ivato","Dzaoudzi","Sainte-Marie"], a: 0 },
  { c: "Madagascar", l: 3, q: "En quelle année a eu lieu l'insurrection malgache du 29 mars ?", o: ["1947","1958","1946","1960"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quelle est la hauteur du Maromokotro, plus haut sommet de Madagascar ?", o: ["2 876 m","2 658 m","2 834 m","3 012 m"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quelle est la saison des cyclones à Madagascar ?", o: ["janvier à mars","juin à août","septembre à novembre","avril à juin"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la monnaie du Japon ?", o: ["le yen","le won","le yuan","le baht"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la monnaie du Royaume-Uni ?", o: ["la livre sterling","l'euro","le dollar","le franc"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la monnaie de la Chine ?", o: ["le yuan","le yen","le won","la roupie"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la monnaie de la Suisse ?", o: ["le franc suisse","l'euro","la livre","la couronne"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la monnaie de l'Inde ?", o: ["la roupie","le taka","la birr","le rand"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de cordes a une guitare classique ?", o: ["6","4","8","12"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de cordes a un violon ?", o: ["4","3","5","6"], a: 0 },
  { c: "Monde", l: 1, q: "Quel instrument possède 88 touches ?", o: ["le piano","le clavecin","l'accordéon","le xylophone"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de dents compte un adulte ?", o: ["32","28","36","30"], a: 0 },
  { c: "Monde", l: 1, q: "Quel organe pompe le sang dans le corps ?", o: ["le cœur","le poumon","le foie","le rein"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la formule chimique de l'eau ?", o: ["H2O","CO2","O2","NaCl"], a: 0 },
  { c: "Monde", l: 2, q: "Quel métal est liquide à température ambiante ?", o: ["le mercure","l'aluminium","le cuivre","l'or"], a: 0 },
  { c: "Monde", l: 1, q: "Lequel de ces animaux est un mammifère ?", o: ["la baleine","le requin","le pingouin","la tortue"], a: 0 },
  { c: "Monde", l: 1, q: "Lequel de ces animaux est un reptile ?", o: ["le crocodile","la grenouille","le dauphin","l'aigle"], a: 0 },
  { c: "Monde", l: 1, q: "Quel oiseau ne sait pas voler ?", o: ["le manchot","l'aigle","le faucon","le pigeon"], a: 0 },
  { c: "Monde", l: 1, q: "Quel animal possède une trompe ?", o: ["l'éléphant","la girafe","le rhinocéros","l'hippopotame"], a: 0 },
  { c: "Monde", l: 2, q: "Quel gaz dégagent les plantes lors de la photosynthèse ?", o: ["le dioxygène","le dioxyde de carbone","l'azote","le méthane"], a: 0 },
  { c: "Monde", l: 1, q: "Combien d'océans y a-t-il sur Terre ?", o: ["5","4","3","7"], a: 0 },
  { c: "Monde", l: 1, q: "Dans quel pays se trouve la grande muraille ?", o: ["la Chine","le Japon","la Corée du Sud","l'Inde"], a: 0 },
  { c: "Monde", l: 1, q: "Quel pays est surnommé « le pays du soleil levant » ?", o: ["le Japon","la Chine","la Corée du Sud","la Thaïlande"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle ville est traversée par la Tamise ?", o: ["Londres","Paris","Rome","Berlin"], a: 0 },
  { c: "Monde", l: 2, q: "Quel est le plus long fleuve d'Afrique ?", o: ["le Nil","le Congo","le Zambèze","le Niger"], a: 0 },
  { c: "Monde", l: 2, q: "Quel canal relie l'Atlantique au Pacifique ?", o: ["le canal de Panamá","le canal de Suez","le canal de Corinthe","le canal du Midi"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle mer sépare l'Arabie de l'Afrique ?", o: ["la mer Rouge","la mer Noire","la mer Caspienne","la mer Jaune"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la plus haute chute d'eau du monde ?", o: ["les chutes Angel","les chutes du Niagara","les chutes d'Iguazú","les chutes Victoria"], a: 0 },
  { c: "Monde", l: 2, q: "Quel volcan a enseveli Pompéi ?", o: ["le Vésuve","l'Etna","le Stromboli","le mont Fuji"], a: 0 },
  { c: "Monde", l: 2, q: "Quel animal est le symbole de l'Australie ?", o: ["le kangourou","le koala","le dingo","le pélican"], a: 0 },
  { c: "Monde", l: 1, q: "Quel animal change de couleur pour se camoufler ?", o: ["le caméléon","le faucon","le poisson rouge","le hibou"], a: 0 },
  { c: "Monde", l: 2, q: "Quel est le plus lourd animal terrestre ?", o: ["l'éléphant d'Afrique","la girafe","l'hippopotame","le rhinocéros"], a: 0 },
  { c: "Monde", l: 3, q: "Quel est le plus grand désert du monde ?", o: ["l'Antarctique","le Sahara","le Gobi","le Kalahari"], a: 0 },
  { c: "Monde", l: 2, q: "Combien de joueurs de rugby par équipe sur le terrain ?", o: ["15","13","11","12"], a: 0 },
  { c: "Monde", l: 1, q: "Quel sport se joue avec un ballon ovale ?", o: ["le rugby","le hockey","le handball","le baseball"], a: 0 },
  { c: "Monde", l: 1, q: "Combien d'anneaux comporte le drapeau olympique ?", o: ["5","4","6","7"], a: 0 },
  { c: "Monde", l: 1, q: "Dans quel pays sont nés les Jeux olympiques ?", o: ["la Grèce","l'Italie","l'Égypte","la Turquie"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle distance fait un marathon ?", o: ["42,195 km","41,195 km","40 km","43,100 km"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de planètes compte le système solaire ?", o: ["8","9","7","10"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle planète est surnommée la planète rouge ?", o: ["Mars","Vénus","Mercure","Saturne"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de satellites naturels a la Terre ?", o: ["1","2","0","4"], a: 0 },
  { c: "Monde", l: 3, q: "Quel est le nom de la lune de Mars ?", o: ["Phobos","Titan","Europe","Ganymède"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de temps met la Terre pour tourner autour du Soleil ?", o: ["365 jours","24 heures","30 jours","100 jours"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de temps la Terre met-elle pour tourner sur elle-même ?", o: ["24 heures","12 heures","48 heures","36 heures"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la température de l'eau qui bout ?", o: ["100 °C","90 °C","80 °C","120 °C"], a: 0 },
  { c: "Monde", l: 1, q: "Qui a inventé le téléphone ?", o: ["Alexander Graham Bell","Thomas Edison","Guglielmo Marconi","Isaac Newton"], a: 0 },
  { c: "Monde", l: 2, q: "En quelle année a commencé la Première Guerre mondiale ?", o: ["1914","1918","1939","1912"], a: 0 },
  { c: "Monde", l: 2, q: "Qui a inventé l'ampoule électrique ?", o: ["Thomas Edison","Nikola Tesla","Alexander Graham Bell","Louis Pasteur"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle scientifique a découvert le radium ?", o: ["Marie Curie","Rosalind Franklin","Ada Lovelace","Jane Goodall"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de la Suisse ?", o: ["Berne","Zurich","Genève","Bâle"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de la Belgique ?", o: ["Bruxelles","Bruges","Anvers","Liège"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale du Portugal ?", o: ["Lisbonne","Madrid","Séville","Porto"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de la Grèce ?", o: ["Athènes","Rome","Sofia","Istanbul"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de la Turquie ?", o: ["Ankara","Istanbul","Izmir","Bursa"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de la Russie ?", o: ["Moscou","Saint-Pétersbourg","Kyiv","Minsk"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de la Chine ?", o: ["Pékin","Shanghai","Hong Kong","Canton"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de la Corée du Sud ?", o: ["Séoul","Pyongyang","Busan","Tokyo"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de la Thaïlande ?", o: ["Bangkok","Hanoï","Phnom Penh","Vientiane"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de l'Argentine ?", o: ["Buenos Aires","Santiago","Lima","Montevideo"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale du Maroc ?", o: ["Rabat","Casablanca","Marrakech","Fès"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de l'Algérie ?", o: ["Alger","Oran","Tunis","Tripoli"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la capitale de la Côte d'Ivoire ?", o: ["Yamoussoukro","Abidjan","Accra","Dakar"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la capitale du Nigeria ?", o: ["Abuja","Lagos","Accra","Khartoum"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de l'Inde ?", o: ["New Delhi","Mumbai","Kolkata","Chennai"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de l'Indonésie ?", o: ["Jakarta","Bali","Singapour","Manille"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de l'Arabie saoudite ?", o: ["Riyad","Dubaï","Doha","Koweït"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de la Norvège ?", o: ["Oslo","Stockholm","Copenhague","Helsinki"], a: 0 },
  // ------------------------------------------------------------ BONUS 3 (300)
  { c: "Madagascar", l: 2, q: "Quel animal insectivore endémique de Madagascar ressemble à un hérisson ?", o: ["le ténrec","le rat","la musaraigne","le hérisson"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quelle est la hauteur du pic Boby, dans l'Andringitra ?", o: ["2 658 m","2 876 m","2 500 m","3 012 m"], a: 0 },
  { c: "Madagascar", l: 1, q: "Que signifie « salama » en malgache ?", o: ["bonjour","au revoir","merci","oui"], a: 0 },
  { c: "Madagascar", l: 1, q: "Que signifie « veloma » en malgache ?", o: ["au revoir","bonjour","merci","pardon"], a: 0 },
  { c: "Madagascar", l: 1, q: "Que signifie « misaotra » en malgache ?", o: ["merci","bonjour","s'il vous plaît","à demain"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le « sifaka » est un…", o: ["lémurien","reptile","oiseau","insecte"], a: 0 },
  { c: "Madagascar", l: 3, q: "En quelle année la République malgache a-t-elle été proclamée ?", o: ["1958","1960","1947","1946"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quel est le nom de l'université publique principale d'Antananarivo ?", o: ["l'Université d'Antananarivo","l'Université de Toliara","l'Université de Mahajanga","l'Université de Toamasina"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quelle est la capitale de la région Analamanga ?", o: ["Antananarivo","Toamasina","Antsirabe","Fianarantsoa"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quelle est la capitale de la région Atsinanana ?", o: ["Toamasina","Antananarivo","Mahajanga","Toliara"], a: 0 },
  { c: "Madagascar", l: 2, q: "Le célèbre marché d'Analakely se trouve dans quelle ville ?", o: ["Antananarivo","Toamasina","Antsirabe","Diego-Suarez"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quelle est la longueur approximative de Madagascar, du nord au sud ?", o: ["1 600 km","800 km","2 400 km","1 200 km"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quelle est la largeur maximale approximative de Madagascar ?", o: ["600 km","250 km","950 km","400 km"], a: 0 },
  { c: "Madagascar", l: 3, q: "Quelle est la saison sèche sur les hautes terres de Madagascar ?", o: ["d'avril à octobre","de novembre à mars","toute l'année","de janvier à avril"], a: 0 },
  { c: "Madagascar", l: 2, q: "Quelle est la capitale de la région Vakinankaratra ?", o: ["Antsirabe","Antananarivo","Fianarantsoa","Ambositra"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale du Mexique ?", o: ["Mexico","Cancún","Guadalajara","Monterrey"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de la Corée du Nord ?", o: ["Pyongyang","Séoul","Pékin","Tokyo"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale de Cuba ?", o: ["La Havane","Santiago","Miami","San Juan"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est la capitale de l'Islande ?", o: ["Reykjavik","Oslo","Copenhague","Helsinki"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la capitale du Danemark ?", o: ["Copenhague","Oslo","Stockholm","Helsinki"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de l'Espagne ?", o: ["Madrid","Barcelone","Séville","Lisbonne"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale des États-Unis ?", o: ["Washington","New York","Los Angeles","Chicago"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la capitale de l'Allemagne ?", o: ["Berlin","Munich","Hambourg","Francfort"], a: 0 },
  { c: "Monde", l: 1, q: "Quel pays est célèbre pour ses tulipes et ses moulins ?", o: ["les Pays-Bas","la Belgique","le Danemark","la Suisse"], a: 0 },
  { c: "Monde", l: 1, q: "Quel monument célèbre a été construit pour l'Exposition universelle de 1889 ?", o: ["la tour Eiffel","l'Arc de Triomphe","Notre-Dame","le Louvre"], a: 0 },
  { c: "Monde", l: 1, q: "Qui a écrit « Harry Potter » ?", o: ["J. K. Rowling","J. R. R. Tolkien","Victor Hugo","Agatha Christie"], a: 0 },
  { c: "Monde", l: 2, q: "Qui a peint le plafond de la chapelle Sixtine ?", o: ["Michel-Ange","Léonard de Vinci","Raphaël","Botticelli"], a: 0 },
  { c: "Monde", l: 2, q: "Quelle est la religion comptant le plus de fidèles dans le monde ?", o: ["le christianisme","l'islam","l'hindouisme","le bouddhisme"], a: 0 },
  { c: "Monde", l: 3, q: "Quelle est approximativement la vitesse du son dans l'air ?", o: ["340 m/s","34 m/s","3 000 m/s","1 000 m/s"], a: 0 },
  { c: "Monde", l: 1, q: "Combien de zéros comporte un million ?", o: ["6","3","9","12"], a: 0 },
  { c: "Monde", l: 1, q: "Quel est le plus petit nombre premier ?", o: ["2","1","3","0"], a: 0 },
  { c: "Monde", l: 1, q: "Quelle est la racine carrée de 144 ?", o: ["12","14","11","13"], a: 0 },
];
